apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx-app
  template:
    metadata:
      labels:
        name: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  type: NodePort
  ports:
  - name: hogeport
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: nginx-app

#apiVersion: v1
#kind: Pod
#metadata:
#  name: nginx-pod
#  labels:
#    name: nginx
#spec:
#  containers:
#    - image: nginx:alpine
#      name: nginx-container
#      ports:
#        - containerPort: 80

